version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./backend:/app
    command: npm start

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"  # Frontend will serve on port 80 inside container, mapped to 5173 locally
    depends_on:
      - backend
